version: "3.8"
services:
  server:
    build: ./server
    container_name: campuspro-server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
